### ISSUE TITLE
Github-Action(upload & download)について学ぶ

### ISSUE THREAD

**Issue by Toraneko0101** [Toraneko0101/git_practice#9]

**Comment by Toraneko0101** [comment]
## コード
```yml
name: artifacts upload workflow

#mainブランチにpushした場合
on:
  push:
    branches: [ "main" ]



jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    # my-artifactというキーワードでpathに該当するファイルをupload
    - run: echo hello > path/to/artifact/world.txt
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/world.txt

    # extra-artifactというキーワードでpathに該当するファイルをupload
    - run: echo hi > path/to/artifact/extra.txt
    - uses: actions/upload-artifact@v3
      with:
        name: extra-artifact
        path: path/to/artifact/extra.txt

    # extra-artifactというキーワードでpathの階層へファイルをdownload
    - uses: actions/download-artifact@v3
      id: test
      with:
        name: extra-artifact
        path: path/to/artifacts

    #downloadパスを表示
    - name: 'Echo download path'
      run: echo ${{steps.test.outputs.download-path}}

    #ファイルの中身を表示
    - name: 'Cat world.txt'
      run: cat ${{steps.test.outputs.download-path}}/extra.txt
```
